name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf
      - name: Install flip-link
        run: cargo install flip-link
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      # no tests available for now => no test step as it'd fail otherwise
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
