name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
          components: rustfmt clippy
      - name: Install flip-link
        run: cargo install flip-link
      - name: build
        run: cargo build ${{ matrix.features }}
      - name: check
        run: cargo check ${{ matrix.features }}
      # no tests available for now => no test step as it'd fail otherwise
      - name: check formatting
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy ${{ matrix.features }}
      - name: audit
        run: cargo audit
